// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tf_dp
NumericVector tf_dp(int n, NumericVector y, double lam);
RcppExport SEXP flam_tf_dp(SEXP nSEXP, SEXP ySEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    __result = Rcpp::wrap(tf_dp(n, y, lam));
    return __result;
END_RCPP
}
// updatecolumn
void updatecolumn(NumericMatrix thetamat, NumericVector column, int colnum, int nrow);
RcppExport SEXP flam_updatecolumn(SEXP thetamatSEXP, SEXP columnSEXP, SEXP colnumSEXP, SEXP nrowSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type thetamat(thetamatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type column(columnSEXP);
    Rcpp::traits::input_parameter< int >::type colnum(colnumSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    updatecolumn(thetamat, column, colnum, nrow);
    return R_NilValue;
END_RCPP
}
// updatevector
void updatevector(NumericVector vector, NumericVector update, int length);
RcppExport SEXP flam_updatevector(SEXP vectorSEXP, SEXP updateSEXP, SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type vector(vectorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type update(updateSEXP);
    Rcpp::traits::input_parameter< int >::type length(lengthSEXP);
    updatevector(vector, update, length);
    return R_NilValue;
END_RCPP
}
// updateresidual
void updateresidual(NumericVector resid, NumericVector y, NumericMatrix thetamat, int j, int n, int p);
RcppExport SEXP flam_updateresidual(SEXP residSEXP, SEXP ySEXP, SEXP thetamatSEXP, SEXP jSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type resid(residSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type thetamat(thetamatSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    updateresidual(resid, y, thetamat, j, n, p);
    return R_NilValue;
END_RCPP
}
// calcsum
double calcsum(NumericMatrix thetamat, int n, int p);
RcppExport SEXP flam_calcsum(SEXP thetamatSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type thetamat(thetamatSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    __result = Rcpp::wrap(calcsum(thetamat, n, p));
    return __result;
END_RCPP
}
// order_
IntegerVector order_(NumericVector x);
RcppExport SEXP flam_order_(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(order_(x));
    return __result;
END_RCPP
}
// maxLambda_a1_C_single
double maxLambda_a1_C_single(NumericVector ycenter, NumericVector xcol, int n);
RcppExport SEXP flam_maxLambda_a1_C_single(SEXP ycenterSEXP, SEXP xcolSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ycenter(ycenterSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xcol(xcolSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(maxLambda_a1_C_single(ycenter, xcol, n));
    return __result;
END_RCPP
}
// ordertheta
NumericVector ordertheta(NumericMatrix thetamat, IntegerMatrix orderx, int i, int n);
RcppExport SEXP flam_ordertheta(SEXP thetamatSEXP, SEXP orderxSEXP, SEXP iSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type thetamat(thetamatSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type orderx(orderxSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(ordertheta(thetamat, orderx, i, n));
    return __result;
END_RCPP
}
// orderthetamat
NumericMatrix orderthetamat(NumericMatrix thetamat, IntegerMatrix orderx, int n, int p);
RcppExport SEXP flam_orderthetamat(SEXP thetamatSEXP, SEXP orderxSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type thetamat(thetamatSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type orderx(orderxSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    __result = Rcpp::wrap(orderthetamat(thetamat, orderx, n, p));
    return __result;
END_RCPP
}
// flamstep
List flamstep(NumericMatrix initialthetamat, NumericVector y, double lambda, double alpha, int n, int p, IntegerMatrix orderx, IntegerMatrix rankx, double tolerance);
RcppExport SEXP flam_flamstep(SEXP initialthetamatSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP nSEXP, SEXP pSEXP, SEXP orderxSEXP, SEXP rankxSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type initialthetamat(initialthetamatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type orderx(orderxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rankx(rankxSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    __result = Rcpp::wrap(flamstep(initialthetamat, y, lambda, alpha, n, p, orderx, rankx, tolerance));
    return __result;
END_RCPP
}
// flamsteplogistic
List flamsteplogistic(NumericMatrix initialthetamat, NumericVector y, double lambda, double alpha, int n, int p, IntegerMatrix orderx, IntegerMatrix rankx, double tolerance);
RcppExport SEXP flam_flamsteplogistic(SEXP initialthetamatSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP nSEXP, SEXP pSEXP, SEXP orderxSEXP, SEXP rankxSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type initialthetamat(initialthetamatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type orderx(orderxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rankx(rankxSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    __result = Rcpp::wrap(flamsteplogistic(initialthetamat, y, lambda, alpha, n, p, orderx, rankx, tolerance));
    return __result;
END_RCPP
}
